[package]
name = "todo-rusqlite"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
workspace-hack = { version = "0.1", path = "../../crates/workspace-hack" }
