[workspace]
resolver = "2"
members = [ "bins/events","bins/steersman", "crates/errors"]

[workspace.dependencies]
thiserror = "2.0.7"
rdkafka = { version = "0.37.0", features = ["tracing"] }

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Joel DSouza <joel@tixlys.com>"]

[workspace.metadata.crane]
name = "tixlys"
