[workspace]
resolver = "2"
members = [
    "crates/*",
]

[workspace.dependencies]
async-trait = "0.1.88"
chrono = { version = "0.4.41", features = ["serde"] }
downcast-rs = "2.0.1"
fake = { version = "4.3.0", features = ["derive", "email_address"] }
futures = "0.3.31"
proptest = "1.7.0"
refinery = { version = "0.8.16", features = ["rusqlite"] }
reqwest = "0.12.20"
rusqlite = { version = "0.33.0", features = ["bundled", "trace", "uuid"] }
serde = { version = "1.0.219", features = ["derive", "rc"] }
serde_json = "1.0.140"
smallvec = "1.15.1"
thiserror = "2.0.12"
tokio = { version = "1.45.1", features = ["full"] }
tokio-stream = "0.1.17"
tower = { version = "0.5.2", features = ["util"] }
tower-http = { version = "0.6.6", features = ["trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
uuid = { version = "1.17.0", features = ["v7", "fast-rng", "serde", "v4"] }

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Joel DSouza <joel@devrandom.co>"]
repository = "https://github.com/nexus/nexus-core"

[workspace.metadata.crane]
name = "nexus"
