[workspace]
resolver = "2"
members = [
    "bins/*",
    "crates/*",
]

[workspace.dependencies]
argon2 = "0.5.3"
async-trait = "0.1.88"
axum = { version = "0.8.4", features = ["macros"] }
chrono = { version = "0.4.41", features = ["serde"] }
futures = "0.3.31"
password-hash = { version = "0.5.0", features = ["rand_core", "getrandom", "alloc"] }
refinery = { version = "0.8.16", features = ["rusqlite"] }
reqwest = "0.12.20"
rusqlite = { version = "0.33.0", features = ["bundled", "trace", "uuid"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
smallvec = "1.15.1"
thiserror = "2.0.12"
tokio = { version = "1.45.1", features = ["full"] }
tokio-stream = "0.1.17"
tower = { version = "0.5.2", features = ["util"] }
tower-http = { version = "0.6.6", features = ["trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
ulid = { version = "1.2.1", features = ["serde"] }
utoipa = { version = "5.4.0", features = ["axum_extras"] }
utoipa-axum = { version = "0.2.0", features = ["debug"] }
utoipa-swagger-ui = { version = "9.0.2", features = ["axum", "vendored"] }
utoipa-swagger-ui-vendored = "0.1.2"
uuid = { version = "1.17.0", features = ["v7", "fast-rng", "serde"] }
validator = { version = "0.20.0", features = ["derive"] }

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
authors = ["Joel DSouza <joel@tixlys.com>"]
repository = "https://github.com/tixlys/tixlys-core"

[workspace.metadata.crane]
name = "tixlys"
