[workspace]
resolver = "2"
members = ["bins/events", "crates/cqrs", "crates/errors"]

[workspace.dependencies]
chrono = "0.4.39"
sqlx = { version = "0.8.3", features = ["sqlite", "migrate", "runtime-tokio-rustls"] }
thiserror = "2.0.7"
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
ulid = { version = "1.1.3", features = ["serde"] }
tower = { version = "0.5.2", features = ["util"] }

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Joel DSouza <joel@tixlys.com>"]
repository = "https://github.com/tixlys/tixlys-core"

[workspace.metadata.crane]
name = "tixlys"
