[workspace]
resolver = "2"
members = ["bins/events", "crates/errors"]

[workspace.dependencies]
chrono = "0.4.39"
thiserror = "2.0.7"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Joel DSouza <joel@tixlys.com>"]

[workspace.metadata.crane]
name = "tixlys"
