# fly.toml app configuration file generated for tixlys-core on 2025-05-02T14:34:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tixlys-auth-dev'
primary_region = 'arn'

[build]
  image = 'ghcr.io/tixlys/tixlys-core/auth'

[[vm]]
  size = 'shared-cpu-1x'

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]


  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true


  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
