[workspace]
git_release_enable = true
git_tag_enable = true
# workspace-hack is disabled before publishing, which dirties the tree
allow_dirty = true

# workspace-hack must not be published
[[package]]
name = "workspace-hack"
publish = false
release = false

# Examples are not published
[[package]]
name = "nexus-example-inmemory"
publish = false
release = false

[[package]]
name = "nexus-example-store-and-kernel"
publish = false
release = false

[[package]]
name = "nexus-example-store-inmemory"
publish = false
release = false

[[package]]
name = "nexus-cross-crate-test"
publish = false
release = false
