DATABASE_URL: ENC[AES256_GCM,data:bHFGfhixB6OmfzLhNqXaw0Q=,iv:7WxjHUk4IaIpu1puzY7nc0EI93rA2XQ8AV6A18WtN2E=,tag:XRleArn7oBZ1gTbCdsbVVA==,type:str]
sops:
    age:
        - recipient: age1przc5apvvpwlhkn7xryxhueydeue06ckqgnv3waxnqqvw0ngpd9qj528fr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMWhCemxZZmJ3NGpYTjVS
            WjU2VzVPeVJ4Yy9SUmdxV08zVVp0Q0RWT3lrCkFhZzlaWE53d0dxMWFDTjlkU0Nt
            eHp5dkh2RXFUU3hvZjlJNHF4QXZnNmsKLS0tIDBNa2NvWjQ0R012TEVsRUQ1R0VY
            K3hrcDM5MHhsR3FYTG56bFRocklaL28Kw0vapMDPjsiyoNYZ9FV1vigChabod2kj
            qXMLz9ImamJRcfw5lsx6S6yJhJANJ999Q9lCH4P1jX4S18zm535ztQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-08T21:05:53Z"
    mac: ENC[AES256_GCM,data:ILtq4b6YJAStkMbkcNcRCTXyHB4gAp9B0woKMZzAIh+YLGbDKe5oDSXpvXRMxnF35rqQrM3+l5Wp/RbKdQqcWByiwuJenlCyZL++2z8ynzdAj8q3x1qIfWdCP15LzT+/9HiS/+LFIFL8DgJ1AGFGUq8BQnvWG8AeC27Nk4u0TI8=,iv:hdZQfn3TMdlsN177imw3L06pAp+F9euFZK1Ya7htvqU=,tag:N/Z9/HgvO5plGd9deW4wLg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
