[package]
name = "steersman"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
pingora = { version = "0.4.0", features = ["proxy"] }
tokio = { workspace = true, features = ["full"] }
