[package]
name = "nexus-macros"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
nexus = { path = "../nexus" }
workspace-hack = { version = "0.1.0", path = "../workspace-hack" }
