[package]
name = "meow_diator"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror = { workspace = true }
workspace-hack = { version = "0.1.0", path = "../workspace-hack" }
