[package]
name = "workspace-hack"
version = "0.1.0"
description = "workspace-hack package, managed by hakari"
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

# The parts of the file between the BEGIN HAKARI SECTION and END HAKARI SECTION comments
# are managed by hakari.

### BEGIN HAKARI SECTION
[dependencies]
chrono = { version = "0.4" }
crypto-common = { version = "0.1", default-features = false, features = ["std"] }
digest = { version = "0.10", features = ["mac", "std"] }
flate2 = { version = "1", default-features = false, features = ["rust_backend", "zlib-ng"] }
futures-channel = { version = "0.3", features = ["sink"] }
futures-executor = { version = "0.3" }
futures-io = { version = "0.3" }
futures-sink = { version = "0.3" }
futures-task = { version = "0.3", default-features = false, features = ["std"] }
futures-util = { version = "0.3", default-features = false, features = ["async-await-macro", "channel", "io", "sink"] }
getrandom-6f8ce4dd05d13bba = { package = "getrandom", version = "0.2", default-features = false, features = ["std"] }
hashbrown = { version = "0.15" }
indexmap = { version = "2", features = ["serde"] }
lock_api = { version = "0.4", features = ["arc_lock"] }
log = { version = "0.4", default-features = false, features = ["std"] }
num-traits = { version = "0.2", default-features = false, features = ["i128", "std"] }
parking_lot = { version = "0.12", features = ["arc_lock"] }
regex = { version = "1" }
regex-automata = { version = "0.4", default-features = false, features = ["dfa-onepass", "hybrid", "meta", "nfa-backtrack", "perf-inline", "perf-literal", "unicode"] }
regex-syntax = { version = "0.8" }
serde = { version = "1", features = ["alloc", "derive", "rc"] }
sha2 = { version = "0.10" }
smallvec = { version = "1", default-features = false, features = ["const_new"] }
sqlx-core = { version = "0.8", features = ["_rt-tokio", "_tls-rustls-ring-webpki", "any", "json", "migrate", "offline"] }
sqlx-sqlite = { version = "0.8", default-features = false, features = ["any", "bundled", "json", "migrate", "offline"] }
sync_wrapper = { version = "1", default-features = false, features = ["futures"] }
tokio = { version = "1", features = ["full", "test-util"] }
tokio-stream = { version = "0.1", features = ["fs"] }
tower = { version = "0.5", default-features = false, features = ["log", "make", "util"] }
tracing = { version = "0.1", features = ["log"] }
tracing-core = { version = "0.1" }

[build-dependencies]
cc = { version = "1", default-features = false, features = ["parallel"] }
crypto-common = { version = "0.1", default-features = false, features = ["std"] }
digest = { version = "0.10", features = ["mac", "std"] }
flate2 = { version = "1", default-features = false, features = ["rust_backend", "zlib-ng"] }
futures-channel = { version = "0.3", features = ["sink"] }
futures-executor = { version = "0.3" }
futures-io = { version = "0.3" }
futures-sink = { version = "0.3" }
futures-task = { version = "0.3", default-features = false, features = ["std"] }
futures-util = { version = "0.3", default-features = false, features = ["async-await-macro", "channel", "io", "sink"] }
getrandom-6f8ce4dd05d13bba = { package = "getrandom", version = "0.2", default-features = false, features = ["std"] }
hashbrown = { version = "0.15" }
indexmap = { version = "2", features = ["serde"] }
lock_api = { version = "0.4", features = ["arc_lock"] }
log = { version = "0.4", default-features = false, features = ["std"] }
num-traits = { version = "0.2", default-features = false, features = ["i128", "std"] }
parking_lot = { version = "0.12", features = ["arc_lock"] }
regex = { version = "1" }
regex-automata = { version = "0.4", default-features = false, features = ["dfa-onepass", "hybrid", "meta", "nfa-backtrack", "perf-inline", "perf-literal", "unicode"] }
regex-syntax = { version = "0.8" }
serde = { version = "1", features = ["alloc", "derive", "rc"] }
sha2 = { version = "0.10" }
smallvec = { version = "1", default-features = false, features = ["const_new"] }
sqlx-core = { version = "0.8", features = ["_rt-tokio", "_tls-rustls-ring-webpki", "any", "json", "migrate", "offline"] }
sqlx-sqlite = { version = "0.8", default-features = false, features = ["any", "bundled", "json", "migrate", "offline"] }
syn = { version = "2", features = ["extra-traits", "fold", "full", "visit", "visit-mut"] }
tokio = { version = "1", features = ["full", "test-util"] }
tokio-stream = { version = "0.1", features = ["fs"] }
tracing = { version = "0.1", features = ["log"] }
tracing-core = { version = "0.1" }

[target.x86_64-unknown-linux-gnu.dependencies]
bitflags = { version = "2", default-features = false, features = ["std"] }
getrandom-468e82937335b1c9 = { package = "getrandom", version = "0.3", default-features = false, features = ["std"] }
hyper = { version = "1", features = ["client", "http1", "http2", "server"] }
hyper-util = { version = "0.1", features = ["client-legacy", "http1", "http2", "server", "service"] }
libc = { version = "0.2", features = ["extra_traits"] }
miniz_oxide = { version = "0.8", default-features = false, features = ["with-alloc"] }
tower = { version = "0.5", default-features = false, features = ["timeout"] }

[target.x86_64-unknown-linux-gnu.build-dependencies]
bitflags = { version = "2", default-features = false, features = ["std"] }
getrandom-468e82937335b1c9 = { package = "getrandom", version = "0.3", default-features = false, features = ["std"] }
libc = { version = "0.2", features = ["extra_traits"] }
miniz_oxide = { version = "0.8", default-features = false, features = ["with-alloc"] }

### END HAKARI SECTION
