[package]
name = "workspace-hack"
version = "0.1.0"
description = "workspace-hack package, managed by hakari"
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

# The parts of the file between the BEGIN HAKARI SECTION and END HAKARI SECTION comments
# are managed by hakari.

### BEGIN HAKARI SECTION
[dependencies]
chrono = { version = "0.4", features = ["serde"] }
futures-channel = { version = "0.3", default-features = false, features = ["sink", "std"] }
futures-core = { version = "0.3" }
futures-sink = { version = "0.3", default-features = false, features = ["std"] }
futures-task = { version = "0.3", default-features = false, features = ["std"] }
futures-util = { version = "0.3", default-features = false, features = ["async-await-macro", "channel", "io", "sink"] }
libsqlite3-sys = { version = "0.31", features = ["bundled"] }
memchr = { version = "2" }
num-traits = { version = "0.2", default-features = false, features = ["std"] }
refinery-core = { version = "0.8", features = ["rusqlite", "toml"] }
rusqlite = { version = "0.33", default-features = false, features = ["bundled", "chrono", "trace", "uuid"] }
serde = { version = "1", features = ["derive", "rc"] }
smallvec = { version = "1", default-features = false, features = ["const_generics"] }
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["fast-rng", "serde", "v4", "v7"] }

[build-dependencies]
chrono = { version = "0.4", features = ["serde"] }
futures-channel = { version = "0.3", default-features = false, features = ["sink", "std"] }
futures-core = { version = "0.3" }
futures-sink = { version = "0.3", default-features = false, features = ["std"] }
futures-task = { version = "0.3", default-features = false, features = ["std"] }
futures-util = { version = "0.3", default-features = false, features = ["async-await-macro", "channel", "io", "sink"] }
libsqlite3-sys = { version = "0.31", features = ["bundled"] }
memchr = { version = "2" }
num-traits = { version = "0.2", default-features = false, features = ["std"] }
proc-macro2 = { version = "1", features = ["span-locations"] }
refinery-core = { version = "0.8", features = ["rusqlite", "toml"] }
rusqlite = { version = "0.33", default-features = false, features = ["bundled", "chrono", "trace", "uuid"] }
serde = { version = "1", features = ["derive", "rc"] }
smallvec = { version = "1", default-features = false, features = ["const_generics"] }
syn = { version = "2", features = ["extra-traits", "fold", "full", "visit", "visit-mut"] }
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["fast-rng", "serde", "v4", "v7"] }

[target.x86_64-unknown-linux-gnu.dependencies]
bitflags = { version = "2", default-features = false, features = ["std"] }
libc = { version = "0.2" }

[target.x86_64-unknown-linux-gnu.build-dependencies]
bitflags = { version = "2", default-features = false, features = ["std"] }
libc = { version = "0.2" }

### END HAKARI SECTION
