[package]
name = "workspace-hack"
version = "0.1.0"
description = "workspace-hack package, managed by hakari"
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

# The parts of the file between the BEGIN HAKARI SECTION and END HAKARI SECTION comments
# are managed by hakari.

### BEGIN HAKARI SECTION
[dependencies]
digest = { version = "0.10", features = ["mac", "std"] }
hashbrown = { version = "0.15", default-features = false, features = ["default-hasher", "inline-more"] }
idna = { version = "1" }
indexmap = { version = "2", features = ["serde"] }
log = { version = "0.4", default-features = false, features = ["std"] }
memchr = { version = "2" }
regex = { version = "1" }
regex-automata = { version = "0.4", default-features = false, features = ["dfa-onepass", "hybrid", "meta", "nfa-backtrack", "perf-inline", "perf-literal", "unicode"] }
regex-syntax = { version = "0.8" }
serde = { version = "1", features = ["derive", "rc"] }
smallvec = { version = "1", default-features = false, features = ["const_new"] }
sync_wrapper = { version = "1", default-features = false, features = ["futures"] }
tokio = { version = "1", features = ["full"] }
tower = { version = "0.5", default-features = false, features = ["log", "make", "util"] }
tracing = { version = "0.1", features = ["log"] }
tracing-core = { version = "0.1" }

[build-dependencies]
digest = { version = "0.10", features = ["mac", "std"] }
hashbrown = { version = "0.15", default-features = false, features = ["default-hasher", "inline-more"] }
indexmap = { version = "2", features = ["serde"] }
log = { version = "0.4", default-features = false, features = ["std"] }
memchr = { version = "2" }
proc-macro2 = { version = "1" }
quote = { version = "1" }
regex = { version = "1" }
regex-automata = { version = "0.4", default-features = false, features = ["dfa-onepass", "hybrid", "meta", "nfa-backtrack", "perf-inline", "perf-literal", "unicode"] }
regex-syntax = { version = "0.8" }
serde = { version = "1", features = ["derive", "rc"] }
syn = { version = "2", features = ["extra-traits", "fold", "full", "visit", "visit-mut"] }

[target.x86_64-unknown-linux-gnu.dependencies]
tower = { version = "0.5", default-features = false, features = ["timeout"] }
tower-http = { version = "0.6", features = ["follow-redirect", "trace"] }

### END HAKARI SECTION
