[package]
name = "nexus"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
nexus-macros = { version = "0.1.0", path = "../nexus-macros", optional = true }
serde = { workspace = true, features = ["derive"] }
smallvec = { workspace = true }
thiserror = { workspace = true }
tokio-stream = { workspace = true }
tower = { workspace = true, features = ["util"] }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v7", "fast-rng", "serde"] }
workspace-hack = { version = "0.1.0", path = "../workspace-hack" }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[features]
default = []
derive = ["nexus-macros"]
