[package]
name = "users"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
workspace-hack = { version = "0.1.0", path = "../../crates/workspace-hack" }
