name: checks
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v29
      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: build-${{ runner.os }}-${{ hashFiles('**/Cargo.toml', 'Cargo.toml', 'flake.nix', 'flake.lock', 'Cargo.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1073741824
          purge: true
          purge-prefixes: cache-${{ runner.os }}-
          purge-created: 0
          purge-primary-key: never
      - name: Flake Checking
        run: nix flake check
## TODO: run integration tests if its a pull request into main
