name: deploys
concurrency: production
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-dept: 0
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v29
      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: build-${{ runner.os }}-${{ hashFiles('**/Cargo.toml', 'Cargo.toml', 'flake.nix', 'flake.lock', 'Cargo.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1073741824
          purge: true
          purge-prefixes: cache-${{ runner.os }}-
          purge-created: 0
          purge-primary-key: never
      - name: Build and Push Image using Nix and Skopeo
        env:
          REGISTRY_URL: ghcr.io
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_NAME: ${{ github.repository_owner }}/${{ github.event.repository.name }}/auth
          IMAGE_TAG: ${{ github.sha }}
        run: nix build .#auth --out-link auth-stream
