
name: tixlys pull request checks
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  checks:
    name: check tixlys-core
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v4
    - name: install nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: nix flake check
      run: nix flake check
