name: tixlys-core releases
on:
  push:
    branches:
      - main
      - dev
jobs:
  install:
    name: check tixlys-core
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v4
    - name: install nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable


## TODO: release steps
## 1. bump minor version
## 3 . nix docker build image
## 4 . upload oci image artifact to ghcr
