name: tixlys-core releases
on:
  push:
    branches:
      - main
      - dev
jobs:
  release:
    if: github.ref == 'refs/heads/main'
    needs: checks


## TODO: release steps
## 1. bump minor version
## 3 . nix docker build image
## 4 . upload oci image artifact to ghcr
