name: releases
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depts: 0
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Install nix
        uses: nixbuild/nix-quick-install-action@v29
      - name: Run release
        uses: release-plz/action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
  release-pr:
    name: Release PR
    runs-on: ubuntu-latest
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install nix
        uses: nixbuild/nix-quick-install-action@v29
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
